### ISSUE TITLE
Schema alterations: dropping wrong column after deleting system field from module

### ISSUE THREAD

**Issue by martkaczmarek** [cortezaproject/corteza#1581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9.1

### Current Behavior

When trying to delete two system fields from module with MSSQL data source:
![image](https://github.com/cortezaproject/corteza/assets/31852710/cfa6b175-ccef-45ff-97cc-9777f05829ff)
changing to:
![image](https://github.com/cortezaproject/corteza/assets/31852710/dfc0e044-3a41-4903-a639-659a05c01ccd)
Corteza should propose deleting columns _rel_namespace_ and _rel_module_, existing in the table:
![image](https://github.com/cortezaproject/corteza/assets/31852710/a078ecd8-fb55-4144-81d9-2845dc91be7b)
but instead it tries to delete columns called _namespaceID_ and _moduleID_:
![image](https://github.com/cortezaproject/corteza/assets/31852710/af62c675-85d8-4451-b29b-924e2cd53209)
SQL logs also indicate that the ALTER command contains wrong column name. 

### Environment and versions

```markdown
MSSQL 2019
Corteza 2023.9.1 Docker install
```

**Comment by tjerman** [comment]
Damn, nice catch

**Comment by martkaczmarek** [comment]
@tjerman you can always count on me finding weird edge cases 😄

**Comment by tjerman** [comment]
Should be resolved with the next patch; I incorrectly resolved attr identifiers due to different codec definitions

```
# Fixed

## What

DAL schema alterations generating incorrect attribute identifiers when attempting to alter to column.

## How

taking attribute store codec into account when generating DDL queries.

## Ref

monorepo 2023.9.x `3e1d7bd42`
```

**Comment by martkaczmarek** [comment]
@tjerman I think it's not fixed:
![image](https://github.com/cortezaproject/corteza/assets/31852710/94a77ca8-3ad7-4969-8545-835d82feaeca)
Installed latest 2023.9.2

**Comment by tjerman** [comment]
Checking it out
