### ISSUE TITLE
Cannot upload images for application logo in Admin Area

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#1722]
https://forum.cortezaproject.org/t/namespace-image/1853/2

**Comment by Fajfa** [comment]
Fixed: https://github.com/cortezaproject/corteza/commit/0456fe4f3e2e127dbccc76d131bbd3d706829133
@katrinDY  Please double check other uploaders (namespace/module/chart and so on if they work)

**Comment by katrinDY** [comment]
The issue is still present when trying to upload a png for an app in admin

**Comment by Fajfa** [comment]
@katrinDY  Make sure you rebuild libraries since it works for me normally

**Comment by katrinDY** [comment]
All good now :)
