### ISSUE TITLE
When I try to filter by a checkbox field I get a DB error

### ISSUE THREAD

**Issue by skamensky** [cortezaproject/corteza#583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2022.9.x

### Current Behavior

When filtering by a checkbox column, I get the error `Could not load record list: pq: syntax error at or near "$1"`

The full error from the DB logs is:

```
corteza_db_1        | 2022-12-01 06:29:00.212 UTC [18145] ERROR:  syntax error at or near "$1" at character 1316
corteza_db_1        | 2022-12-01 06:29:00.212 UTC [18145] STATEMENT:  SELECT "ImportMerchant"."ImportDate", "ImportMerchant"."LeadSource", "ImportMerchant"."BusinessName", "ImportMerchant"."Phone", "ImportMerchant"."AlternatePhone", "ImportMerchant"."CreditScore", "ImportMerchant"."FirstName", "ImportMerchant"."LastName", "ImportMerchant"."BusinessAddress", "ImportMerchant"."MailingAddress", "ImportMerchant"."Fax", "ImportMerchant"."Zip", "ImportMerchant"."MonthlyRevenue", "ImportMerchant"."FundedDate", "ImportMerchant"."EIN", "ImportMerchant"."ApprovalAmount", "ImportMerchant"."RequestingAmount", "ImportMerchant"."DateBusinessStarted", "ImportMerchant"."Industry", "ImportMerchant"."Email", "ImportMerchant"."AlternativeEmail", "ImportMerchant"."Merchant", "ImportMerchant"."Processed_calc", "ImportMerchant"."ImportJob", "ImportMerchant"."Notes", "ImportMerchant"."Error", "ImportMerchant"."NumMergeFields", "ImportMerchant"."id", "ImportMerchant"."rel_module", "ImportMerchant"."deleted_by", "ImportMerchant"."rel_namespace", "ImportMerchant"."revision", "ImportMerchant"."meta", "ImportMerchant"."owned_by", "ImportMerchant"."created_at", "ImportMerchant"."created_by", "ImportMerchant"."updated_at", "ImportMerchant"."updated_by", "ImportMerchant"."deleted_at" FROM "ImportMerchant" WHERE (("ImportMerchant"."deleted_at" IS NULL) AND ("ImportMerchant"."Processed_calc" IS $1)) ORDER BY "ImportMerchant"."BusinessName" ASC NULLS FIRST, "ImportMerchant"."id" ASC NULLS FIRST LIMIT $2
```

![image](https://user-images.githubusercontent.com/19151369/204981424-fceaccd2-ad43-4e2f-82f6-b7e87dfd795a.png)

### Expected Behavior

The list filters properly

### Steps To Reproduce

Create physical table, and physical column of type checkbox.
Make a list view, try to filter by it.

### Anything else?

If you point me to where you think the error is in the code I don't mind fixing it

**Comment by skamensky** [comment]
Bump

**Comment by vicpatel** [comment]
This is fixed by https://github.com/cortezaproject/corteza/commit/8e5d63c09b921c83571a6d99408cfc78e41291ef.

**Comment by skamensky** [comment]
I'm running `2023.3.0-dev.1` and still have the issue

![image](https://user-images.githubusercontent.com/19151369/213871173-255919f4-3f45-47d9-a7eb-49be74482a3a.png)


Are you certain this was fixed?
